{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-trekcolors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/trekcolors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/trekcolors/trekcolors_{{ version }}.tar.gz
  sha256: bb7898e5cbeff9740383d46120c67327f7e6d6630324507b6da27b9b41e45466

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('trekcolors')"           # [not win]
    - "\"%R%\" -e \"library('trekcolors')\""  # [win]

about:
  home: https://github.com/leonawicz/trekcolors
  license: MIT
  summary: Provides a dataset of predefined color palettes based on the Star Trek science fiction series, associated color palette functions, and additional functions for generating customized palettes that are on theme. The package also offers functions for applying the palettes to plots made using the 'ggplot2' package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: trekcolors
# Title: Star Trek Color Palettes
# Version: 0.1.1
# Authors@R: person("Matthew", "Leonawicz", email = "matt_leonawicz@esource.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-9452-2771"))
# Description: Provides a dataset of predefined color palettes based on the Star Trek science fiction series, associated color palette functions, and additional functions for generating customized palettes that are on theme. The package also offers functions for applying the palettes to plots made using the 'ggplot2' package.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/leonawicz/trekcolors
# BugReports: https://github.com/leonawicz/trekcolors/issues
# Depends: R (>= 2.10)
# Imports: ggplot2
# Suggests: testthat, knitr, rmarkdown, covr
# RoxygenNote: 6.1.1
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-10-15 02:52:51 UTC; Matt
# Author: Matthew Leonawicz [aut, cre] (<https://orcid.org/0000-0001-9452-2771>)
# Maintainer: Matthew Leonawicz <matt_leonawicz@esource.com>
# Repository: CRAN
# Date/Publication: 2019-10-16 11:50:03 UTC
